# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      ##- run: npm install -g @angular/cli
      - run: yarn ng -- build



  deploy:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - deploy
          name: Deploy Master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Deploy"
            else
              echo "No deploy, not master branch"
            fi



workflows:
  version: 2
  
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - develop
                - feature-circleCI
      - deploy:
          filters:
            tag:
              only: /^release-.*/
            branches:
              only:
                - master
              
        
