# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      ##- run: npm install -g @angular/cli
      - run: yarn ng -- build



  deploy_prod:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - run :
          command: |
            'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
            eval $(ssh-agent -s)
            ssh-add <(echo "$DEPLOYMENT_PRIVATE_KEY")
            mkdir -p ~/.ssh
            '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
            scp working_directory $DEPLOYMENT_USER:$DEPLOYMENT_HOST:/var/www/prod_deploy
            ssh $DEPLOYMENT_USER:$DEPLOYMENT_HOST
            cd /var/www/prod_deploy
            yarn install
            yarn build --prod 
            cp /var/www/prod/config.js ./
            cd /var/www
            mv ./prod ./prod_old
            mv ./prod_deploy ./prod
            cd prod
            pm2 stop prod
            pm2 start --name="prod"
            cd /var/www ; rm -rf prod_old
            echo "Well done !"
        
workflows:
  version: 2
  
  build_n_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - develop
                - feature-circleCI

      - deploy_prod:
          requires:
            - build
          filters:
            #tags:
            #  only: /^release-.*/
            branches:
              only:
                - master
                - feature-circleCI

              
       
